//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoundBitsRecorder.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SoundBitsRecorder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About SoundBits Recorder.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string Advanced {
            get {
                return ResourceManager.GetString("Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author:.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic.
        /// </summary>
        public static string Basic {
            get {
                return ResourceManager.GetString("Basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bits per sample.
        /// </summary>
        public static string BitsPerSample {
            get {
                return ResourceManager.GetString("BitsPerSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2021-06-27 
        ///.
        /// </summary>
        public static string BuildDate {
            get {
                return ResourceManager.GetString("BuildDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to built.
        /// </summary>
        public static string built {
            get {
                return ResourceManager.GetString("built", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This change will take effect next time you open this application..
        /// </summary>
        public static string ChangeNextTime {
            get {
                return ResourceManager.GetString("ChangeNextTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company:.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording in progress. Are you sure you want to quit? The audio recorded so far will be saved..
        /// </summary>
        public static string ConfirmInProgress {
            get {
                return ResourceManager.GetString("ConfirmInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device:.
        /// </summary>
        public static string Device {
            get {
                return ResourceManager.GetString("Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording already started..
        /// </summary>
        public static string ErrorAlreadyStarted {
            get {
                return ResourceManager.GetString("ErrorAlreadyStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add or remove devices while recording..
        /// </summary>
        public static string ErrorChangeWhileRecording {
            get {
                return ResourceManager.GetString("ErrorChangeWhileRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least an input or loopback device must be specified..
        /// </summary>
        public static string ErrorNoDevices {
            get {
                return ResourceManager.GetString("ErrorNoDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while recording..
        /// </summary>
        public static string ErrorRecording {
            get {
                return ResourceManager.GetString("ErrorRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while trying to start recording..
        /// </summary>
        public static string ErrorStartRecording {
            get {
                return ResourceManager.GetString("ErrorStartRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing....
        /// </summary>
        public static string Initializing {
            get {
                return ResourceManager.GetString("Initializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Device to Record:.
        /// </summary>
        public static string InputDevice {
            get {
                return ResourceManager.GetString("InputDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licenses.
        /// </summary>
        public static string Licenses {
            get {
                return ResourceManager.GetString("Licenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About SoundBits Recorder.
        /// </summary>
        public static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xit.
        /// </summary>
        public static string MenuExit {
            get {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Language.
        /// </summary>
        public static string MenuLanguage {
            get {
                return ResourceManager.GetString("MenuLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Output Folder....
        /// </summary>
        public static string MenuOutputFolder {
            get {
                return ResourceManager.GetString("MenuOutputFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Settings.
        /// </summary>
        public static string MenuSettings {
            get {
                return ResourceManager.GetString("MenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Start Recording.
        /// </summary>
        public static string MenuStartRecording {
            get {
                return ResourceManager.GetString("MenuStartRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Stop Recording.
        /// </summary>
        public static string MenuStopRecording {
            get {
                return ResourceManager.GetString("MenuStopRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Folder....
        /// </summary>
        public static string OpenFolder {
            get {
                return ResourceManager.GetString("OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Device to Record:.
        /// </summary>
        public static string OutputDevice {
            get {
                return ResourceManager.GetString("OutputDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record sound from input.
        /// </summary>
        public static string RecordFromInput {
            get {
                return ResourceManager.GetString("RecordFromInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record sound from output.
        /// </summary>
        public static string RecordFromOutput {
            get {
                return ResourceManager.GetString("RecordFromOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording....
        /// </summary>
        public static string Recording {
            get {
                return ResourceManager.GetString("Recording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording has stopped..
        /// </summary>
        public static string RecordingStopped {
            get {
                return ResourceManager.GetString("RecordingStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save to:.
        /// </summary>
        public static string SaveTo {
            get {
                return ResourceManager.GetString("SaveTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving....
        /// </summary>
        public static string Saving {
            get {
                return ResourceManager.GetString("Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Recording.
        /// </summary>
        public static string StartRecording {
            get {
                return ResourceManager.GetString("StartRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Recording.
        /// </summary>
        public static string StopRecording {
            get {
                return ResourceManager.GetString("StopRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported sound encoding.
        /// </summary>
        public static string UnsupportedSoundEncoding {
            get {
                return ResourceManager.GetString("UnsupportedSoundEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website:.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
    }
}
